### ISSUE TITLE
Clarify implementation of Profiles

### ISSUE THREAD

**Issue by rglassett** [annemai/storybook#2]
There's currently nothing in the db schema or phase timeline that explains how Profiles will be implemented. Will you have a Profile model in Rails? Will you simply add columns to the User model? Inquiring minds want to know!

**Comment by annemai** [comment]
I updated the phase1 doc to clarify how profiles will be implemented.  I will be having a Profiles controller in rails but not a model.  I will be using JBuilder to construct a JSON object that includes everything(friends, post info, etc)  that will be needed to construct the profile super view.
